webservers:
  hosts:
    django-mmt:
      ansible_host: www.example.com
      ansible_python_interpreter: /usr/bin/python
    localhost:
      ansible_connection: local
      ansible_python_interpreter: /usr/bin/python
