---
- name: Provision server
  hosts: django-mmt
  remote_user: root
  tasks:
    - name: Install aptitude
      apt:
        name: aptitude
        state: latest
        update_cache: true

    - name: Upgrade packages
      apt:
        upgrade: safe

    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - dbus-user-session
          - git
          - python3-dev
          - python3-docker
          - python3-paramiko
          - python3-pip
          - python3-setuptools
          - python3-venv
          - slirp4netns
          - software-properties-common
          - ufw
          - uidmap
          - vim
          - virtualenv
        state: latest
        update_cache: true

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update apt and install docker packages
      apt:
        pkg:
          - docker-ce
          - docker-ce-rootless-extras
          - docker-compose-plugin
        state: latest
        update_cache: true

    - name: Disable password logins
      lineinfile:
        path: /etc/ssh/sshd_config
        search_string: '#PasswordAuthentication yes'
        line: PasswordAuthentication no
        state: present
      notify: Restart ssh service

    - name: Set firewall rule for SSH
      community.general.ufw:
        rule: limit
        port: ssh
        proto: tcp

    - name: Set firewall rules for HTTP/HTTPS
      community.general.ufw:
        rule: allow
        port: '{{ item }}'
        proto: tcp
      loop:
        - http
        - https

    - name: Enable firewall
      community.general.ufw:
        state: enabled

    - name: Create deploy user
      user:
        name: deploy
        shell: /bin/bash
        create_home: yes

    - name: Add deploy user to sudoers file
      community.general.sudoers:
        name: run-docker
        user: deploy
        commands: ALL

    - name: Set authorized key file from local user
      authorized_key:
        user: deploy
        state: present
        key: https://github.com/marcaltmann.keys

  handlers:
    - name: Restart ssh service
      service:
        name: ssh
        state: restarted
